export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_MONTH_EVENTS = 'FETCH_MONTH_EVENTS'
export const FETCH_DAY_EVENTS = 'FETCH_DAY_EVENTS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';